### ISSUE TITLE
error when starting the server

### ISSUE THREAD

**Issue by ghost** [sharkbound/WebsiteCommand#1]
here is the picture: 
![websitecommand errors](https://cloud.githubusercontent.com/assets/10390196/20030084/37ca0db8-a366-11e6-9be5-a14ea5134ea8.png)

**Comment by sharkbound** [comment]
Does this still happen when you remove the plugin?

**Comment by ghost** [comment]
not sure

**Comment by sharkbound** [comment]
try removing the plugin and see if it still happens

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
oh no its not the plugin. is rocket. sorry
